# Generated by Django 2.1.2 on 2019-01-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='universityYear',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year')], default='', max_length=1),
        ),
    ]
