# Generated by Django 2.1.2 on 2019-01-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190110_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(choices=[('BCS', 'BSc Computer Science'), ('BCSM', 'BSc Computer Science and Mathematics'), ('BCSIE', 'BSc Computer Science with Industrial Experience'), ('BCS', 'BSc Computer Science with Management (ITMB)'), ('MCS', 'MSci Computer Science'), ('CSIE', '3rd Year')], default='', max_length=1),
        ),
    ]
