# Generated by Django 2.1.2 on 2019-01-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190110_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subject',
            field=models.CharField(choices=[('BCS', 'BSc Computer Science'), ('BCSM', 'BSc Computer Science and Mathematics'), ('BCSIE', 'BSc Computer Science with Industrial Experience'), ('BCS', 'BSc Computer Science with Management (ITMB)')], default='', max_length=255),
        ),
    ]
