# Generated by Django 2.1.2 on 2019-01-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190110_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='subject',
            field=models.CharField(choices=[('BCS', 'BSc Computer Science'), ('BCSM', 'BSc Computer Science and Mathematics'), ('BCSIE', 'BSc Computer Science with Industrial Experience'), ('BCSWM', 'BSc Computer Science with Management (ITMB)')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.ManyToManyField(to='accounts.Interest'),
        ),
    ]
