# Generated by Django 2.1.2 on 2019-01-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
